version: '3'

services:
  web:
    build: ./fastapi
    ports:
      - "8000:8000"
    restart: always
    env_file: variables.env
    volumes:
      - ./fastapi:/app
    depends_on:
      - mongodb
    links:
      - mongodb
  scrapper-1:
    build: ./scraper
    ports:
      - "80:80"
    volumes:
      - ./scraper:/app
    env_file: variables.env
    depends_on:
      - mongodb
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    env_file: variables.env
    volumes:
      - ./data:/data/db
